// Function to convert currency
async function convertCurrency() {
    const fromCurrency = document.getElementById('fromcurrency').value;
    const toCurrency = document.getElementById('tocurrency').value;
    const amount = parseFloat(document.getElementById('amount_input').value);
    const conversionPaths = document.getElementById("conversionPaths");

    //Function to calculate the finalAmount generated by converting from intermediate to end currency
    async function exchangeArbitrage(interAmount, object){
        const url2 = `https://v6.exchangerate-api.com/v6/${apiKey}/latest/${object.currency}`;
        const response = await fetch(url2);
        const data = await response.json();
        const rate = data.conversion_rates[toCurrency];
        object.indirect = (interAmount * rate).toFixed(3);
    }

    //function to calculate best paths for currency exchange maximizing user profit
    async function calculateBestPaths(fromCurrency, toCurrency, amount) {
        try {
            const response = await fetch(url);
            const data = await response.json();
            const rates = data.conversion_rates;
    
            let paths = [];
            const intermediateCurrencies = Object.keys(rates).filter((currency) => currency !== fromCurrency && currency !== toCurrency);
            
            //convertiing input amount from start currency to intermediate currencies
            intermediateCurrencies.forEach((intermediate) => {
                const convertInter = amount*(rates[intermediate] / rates[fromCurrency]);
                
                //paths stores them as objects
                paths.push({
                    path: `${fromCurrency} to ${intermediate} to ${toCurrency}`,
                    indirect: (convertInter).toFixed(5),
                    currency: intermediate
                });
            });

            //function to call conversions from intermediate to end currency 
            async function processPaths() {
                for (let object of paths) {
                    await exchangeArbitrage(parseFloat(object.indirect), object);  
                }
            }


            processPaths().then(()=>{//executed if Promise is fulfilled
                paths = paths.sort((a, b) => parseFloat(b.indirect) - parseFloat(a.indirect)); //sorting array in decreasing order
    
                const bestPaths = paths.slice(0, 3); // selecting best three paths
                conversionPaths.innerHTML = bestPaths.map((path) => { //add this HTML code 
                return `
                    <li id="paths-displayed">
                        <strong>${path.path}:</strong> 
                        ${path.indirect} ${toCurrency}
                    </li>
                `;
            }).join('');
            });    
        } catch (error) {//in case of error, console gives error and window shows alert popup message
            console.error("Error calculating best paths:", error);
            alert ("Failed to calculate best paths.");
        }
    }  

    if (!fromCurrency || !toCurrency || isNaN(amount)) {//if input not given, alert msg displayed
        alert('Please enter valid currencies and amount.');
        return;
    }

    const apiKey = 'd85f26ac2223a11406f2b178';//replace this key with YOUR_API_KEY of ExchangeRate-API
    const url = `https://v6.exchangerate-api.com/v6/${apiKey}/latest/${fromCurrency}`;

    try {
        const response = await fetch(url);
        if (!response.ok) throw new Error('Failed to fetch exchange rates');

        const data = await response.json();
        const rate = data.conversion_rates[toCurrency]; //stores exchange rates

        if (!rate) { //error shown if rate is not available
            alert(`Conversion rate for ${toCurrency} not available.`);
            return;
        }

        const convertedAmount = (amount * rate).toFixed(2);
        document.getElementById('result').innerText = `${amount} ${fromCurrency} = ${convertedAmount} ${toCurrency}`;
        
        document.getElementById('output').style.display="block";
        
        calculateBestPaths(fromCurrency, toCurrency, amount);
    } catch (error) {
        console.error(error);
        alert('An error occurred. Please try again.');
    }
}

// Event listener for the 'convert' button
document.getElementById('btn').addEventListener('click', convertCurrency);
